# Projecto X Dockerfile
FROM python
MAINTAINER Shinkei <shinkeygentatsu@yahoo.com.mx>
RUN apt-get update && apt-get upgrade -y --force-yes
RUN apt-get autoremove -y --force-yes
RUN pip install --upgrade pip
RUN pip3 install flask mongoengine flask_mongoengine flask_httpauth 